name: build

on:
  push:
    branches:
      - 'x-wf-env'
    tags:
      - 'x-wf-env-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            dotmpe/x-github
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=edge,branch=x-wf-env
            type=match,pattern=x-wf-env-v(.*),group=1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Echo env
        shell: bash
        run: env

      #-
      #  name: Build and push
      #  id: docker_build
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
