name: build

on:
  push:
    branches:
      - 'x-docker-build'
    tags:
      - 'x-docker-build-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            dotmpe/x-github
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=edge,branch=x-docker-build
            type=match,pattern=x-docker-build-v(.*),group=1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
